### ISSUE TITLE
Agregar nuevo campo para email

### ISSUE THREAD

**Issue by luisvillasenor** [sectureags/inventariobi#2]
Modificacion mayor para la version beta en  Modulo de Empleados
Agregar campo nuevo que almacene el correo electronico del empleado.

**Comment by luisvillasenor** [comment]
Solo para tu informacion (FYI)
http://sectureags.github.io/inventariobi/

**Comment by noraescareno** [comment]
Actividad Realizada: Se creo el nuevo campo en la tabla de la BD para almacenar el correo electorico del empleado, se realizaron las modificaciones para las vistas asi como los metodos para el controller y el model.
