### ISSUE TITLE
Cambio de 3 Labels

### ISSUE THREAD

**Issue by luisvillasenor** [sectureags/inventariobi#3]
Cambio menor:
Se solicita cambio en 3 labels:
Usuario de Red --> Usuario de Dominio
Unidad --> pendiente de definir por Julio
Area --> Area de Adscripcion

**Comment by noraescareno** [comment]
Se realizo la modificacion a las vistas de los modal editar y agregar empleado a solicitus del cliente.

**Comment by noraescareno** [comment]
Ya se realizo el cambio del label Usuario de  Red --> Usuario de Dominio y label Area --> Area de Adscripcion.

Queda pendiente el label Unidad a definir por Julio
